/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package windows;

import domain.abstracts.Guerreiro;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marco Dornell
 */
public class Listas extends javax.swing.JDialog {
    
    private LinkedList<Guerreiro>  lado1;
    private LinkedList<Guerreiro>  lado2;
    
    /**
     * Creates new form Listas
     */
    public Listas(java.awt.Frame parent, boolean modal, LinkedList<Guerreiro>  lado1,LinkedList<Guerreiro>  lado2) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.lado1 = lado1;
        this.lado2 = lado2;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblGuerreiro1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGuerreiro2 = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        tblGuerreiro1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        tblGuerreiro1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        tblGuerreiro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Terrans e Protoss", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblGuerreiro1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(44, 40, 332, 340);

        tblGuerreiro2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        tblGuerreiro2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        tblGuerreiro2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Zergs e Nagas", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblGuerreiro2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(471, 40, 320, 340);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(44, 420, 100, 38);
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 830, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        exibe(lado1,lado2);
    }//GEN-LAST:event_formWindowActivated

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void exibe(LinkedList<Guerreiro> lado1,LinkedList<Guerreiro> lado2){
        DefaultTableModel modelTabela1 = (DefaultTableModel) this.tblGuerreiro1.getModel();      
        for(int i = 0; i < lado1.size() && lado1.get(i) != null; i++){
            modelTabela1.addRow(new Object[]{lado1.get(i).getNome(), lado1.get(i).toString()});
        }      
        DefaultTableModel modelTabela2 = (DefaultTableModel) this.tblGuerreiro2.getModel();
        for(int i = 0; i < lado2.size() && lado2.get(i) != null; i++){
            modelTabela2.addRow(new Object[]{lado2.get(i).getNome(), lado2.get(i).toString()});
        }
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Listas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Listas dialog = new Listas(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JTable tblGuerreiro1;
    private javax.swing.JTable tblGuerreiro2;
    // End of variables declaration//GEN-END:variables
}
