/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import control.Battlefield;
import domain.abstracts.Guerreiro;
import java.util.LinkedList;

/**
 *
 * @author Marco Dornell
 */
public class MainWindow extends javax.swing.JFrame {

    private LinkedList<Guerreiro>  lado1;
    private LinkedList<Guerreiro>  lado2;
    private Battlefield batalha;
    /**
     * Creates new form MainWindow
     */
    public MainWindow(LinkedList<Guerreiro>  lado1,LinkedList<Guerreiro>  lado2, Battlefield batalha) {
        initComponents();
        setLocationRelativeTo(null);
        this.lado1 = lado1;
        this.lado2 = lado2;
        this.batalha = batalha;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJogar = new javax.swing.JButton();
        btnListas = new javax.swing.JButton();
        btnInfos = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        btnJogar.setText("Jogar");
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJogar);
        btnJogar.setBounds(243, 127, 150, 49);

        btnListas.setText("Listas");
        btnListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListasActionPerformed(evt);
            }
        });
        getContentPane().add(btnListas);
        btnListas.setBounds(243, 241, 150, 47);

        btnInfos.setText("Infos");
        btnInfos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfosActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfos);
        btnInfos.setBounds(430, 127, 150, 49);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(430, 241, 150, 47);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitle.setText("StarCraft IFES");
        lblTitle.setToolTipText("");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblTitle);
        lblTitle.setBounds(305, 33, 220, 48);
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 830, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        Game game = new Game(null, true,this.lado1,this.lado2,this.batalha);
        game.setVisible(true);
    }//GEN-LAST:event_btnJogarActionPerformed

    private void btnListasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListasActionPerformed
        Listas listas = new Listas(null, true,this.lado1,this.lado2);
        listas.setVisible(true);
    }//GEN-LAST:event_btnListasActionPerformed

    private void btnInfosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfosActionPerformed
        Infos infos = new Infos(null, true,this.batalha,this.lado1,this.lado2);
        infos.setVisible(true);
    }//GEN-LAST:event_btnInfosActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);     
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfos;
    private javax.swing.JButton btnJogar;
    private javax.swing.JButton btnListas;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
